# Generated by Django 3.0.6 on 2020-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_advertisement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
