# Generated by Django 3.0.6 on 2020-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_auto_20200602_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='Social_network',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='UserInstagram',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='UserTwitter',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Userfacebook',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
