# Generated by Django 3.0.6 on 2020-06-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_auto_20200602_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='UserInstagram',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='UserTwitter',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='Userfacebook',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='show_adress',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='show_phones',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='url_website',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='whatsapp',
            field=models.CharField(blank=True, default=None, max_length=11),
        ),
    ]
